Repository Team-BNUY/gamelab_project_bunny, pull requests merged in 2022-04, with the labels that each got.

#88 [Code][Gameplay] Test in throwing mechanic
  Project Bunny/Assets/Animations/Controllers/TestPlayerAC_WithBlendTree.controller
  Project Bunny/Assets/Resources/NetworkPlayerTest.prefab
  Project Bunny/Assets/Resources/NetworkSnowball.prefab
  Project Bunny/Assets/Scripts/Player/NetworkCannon.cs
  Project Bunny/Assets/Scripts/Player/NetworkSnowball.cs
  Project Bunny/Assets/Scripts/Player/NetworkStudentAnimator.cs
  Project Bunny/Assets/Scripts/Player/NetworkStudentController.cs
  Project Bunny/Assets/Scripts/Player/ReadyToAim.cs
  Project Bunny/Assets/Scripts/Player/ReadyToAim.cs.meta
Labels: coding, gameplay

#119 94 AI buf fixes and polishing
  Project Bunny/Assets/Animations/Controllers/StudentAC.controller
  Project Bunny/Assets/Animations/Controllers/TeacherAC.controller
  Project Bunny/Assets/Resources/NetworkCannonball.prefab
  Project Bunny/Assets/Resources/NetworkIceball.prefab
  Project Bunny/Assets/Resources/NetworkPlayerTest.prefab
  Project Bunny/Assets/Scenes/Networking/4-Arena.unity
  Project Bunny/Assets/Scenes/Networking/4-Arena/NavMesh.asset
  Project Bunny/Assets/Scripts/AI/Agents/Student.cs
  Project Bunny/Assets/Scripts/AI/Agents/Teacher.cs
  Project Bunny/Assets/Scripts/Networking/ArenaManager.cs
  Project Bunny/Assets/Scripts/Player/NetworkGiantRollball.cs
  Project Bunny/Assets/Scripts/UnhitOnEnter.cs
  Project Bunny/Assets/Scripts/UnhitOnEnter.cs.meta
Labels: bug

#127 [Code] [Network] Upgraded Lobby Scoreboard
  Project Bunny/Assets/Art/UI/WhiteBoard/BlueTeamWins.png.meta
  Project Bunny/Assets/Art/UI/WhiteBoard/LogoWhiteBoard.png.meta
  Project Bunny/Assets/Art/UI/WhiteBoard/RedTeamWins.png.meta
  Project Bunny/Assets/Prefabs/Art Prefabs/Classroom/Whiteboard_Prefab.prefab
  Project Bunny/Assets/Prefabs/UI/ScoreboardCanvas.prefab
  Project Bunny/Assets/Prefabs/UI/ScoreboardCanvas.prefab.meta
  Project Bunny/Assets/Resources/NetworkIceball.prefab
  Project Bunny/Assets/Resources/ScoreManager.prefab
  Project Bunny/Assets/Scenes/Networking/3-Room.unity
  Project Bunny/Assets/Scripts/Networking/RoomManager.cs
  Project Bunny/Assets/Scripts/ScoreManager.cs
Labels: coding, networking

#138 [Code][Feature] Added Boots color modification
  Project Bunny/Assets/Art/FBX/character/NewBootsMaterial.mat
  Project Bunny/Assets/Art/FBX/character/NewBootsMaterial.mat.meta
  Project Bunny/Assets/Art/FBX/character/PlayerBootsUV.png
  Project Bunny/Assets/Art/FBX/character/PlayerBootsUV.png.meta
  Project Bunny/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  Project Bunny/Assets/Resources/NetworkPlayerTest.prefab
  Project Bunny/Assets/Scenes/Networking/3-Room.unity
  Project Bunny/Assets/Scripts/Networking/ArenaManager.cs
  Project Bunny/Assets/Scripts/Networking/RoomManager.cs
  Project Bunny/Assets/Scripts/Player/CustomizationLocker.cs
  Project Bunny/Assets/Scripts/Player/NetworkStudentController.cs
Labels: bug, coding, Emergency

#140 [Code] [Network] screw you door
  Project Bunny/Assets/Prefabs/Art Prefabs/Classroom/Door_And_Frame_Prefab.prefab
  Project Bunny/Assets/Resources/Door_V2_FBX.prefab
  Project Bunny/Assets/Resources/Door_V2_FBX.prefab.meta
  Project Bunny/Assets/Scenes/Networking/3-Room.unity
  Project Bunny/Assets/Scripts/Networking/NetworkDoor.cs
Labels: coding, networking, Emergency

#150 [Code][Sound] Add bunch of sounds and fix exit walk animation
  Project Bunny/Assets/Audio/sfx/UnclassifiedYet.meta
  Project Bunny/Assets/Audio/sfx/UnclassifiedYet/clockCountdown.wav
  Project Bunny/Assets/Audio/sfx/UnclassifiedYet/clockCountdown.wav.meta
  Project Bunny/Assets/Audio/sfx/UnclassifiedYet/giantRollballBurst_sfx.wav
  Project Bunny/Assets/Audio/sfx/UnclassifiedYet/giantRollballBurst_sfx.wav.meta
  Project Bunny/Assets/Audio/sfx/UnclassifiedYet/iceballHit_sfx.wav
  Project Bunny/Assets/Audio/sfx/UnclassifiedYet/iceballHit_sfx.wav.meta
  Project Bunny/Assets/Audio/sfx/UnclassifiedYet/kidDeath.wav
  Project Bunny/Assets/Audio/sfx/UnclassifiedYet/kidDeath.wav.meta
  Project Bunny/Assets/Audio/sfx/UnclassifiedYet/kidHit_sfx.wav
  Project Bunny/Assets/Audio/sfx/UnclassifiedYet/kidHit_sfx.wav.meta
  Project Bunny/Assets/Audio/sfx/UnclassifiedYet/launch1.wav
  Project Bunny/Assets/Audio/sfx/UnclassifiedYet/launch1.wav.meta
  Project Bunny/Assets/Audio/sfx/UnclassifiedYet/launch2.wav
  Project Bunny/Assets/Audio/sfx/UnclassifiedYet/launch2.wav.meta
  Project Bunny/Assets/Audio/sfx/UnclassifiedYet/ow.wav
  Project Bunny/Assets/Audio/sfx/UnclassifiedYet/ow.wav.meta
  Project Bunny/Assets/Audio/sfx/UnclassifiedYet/rollballRoll_sfx.wav
  Project Bunny/Assets/Audio/sfx/UnclassifiedYet/rollballRoll_sfx.wav.meta
  Project Bunny/Assets/Audio/sfx/UnclassifiedYet/snowballHit_sfx.wav
  Project Bunny/Assets/Audio/sfx/UnclassifiedYet/snowballHit_sfx.wav.meta
  Project Bunny/Assets/Audio/sfx/UnclassifiedYet/snowballThrow_sfx.wav
  Project Bunny/Assets/Audio/sfx/UnclassifiedYet/snowballThrow_sfx.wav.meta
  Project Bunny/Assets/Audio/sfx/UnclassifiedYet/snowball_sfx.wav
  Project Bunny/Assets/Audio/sfx/UnclassifiedYet/snowball_sfx.wav.meta
  Project Bunny/Assets/Audio/sfx/UnclassifiedYet/teacherSuspense.wav
  Project Bunny/Assets/Audio/sfx/UnclassifiedYet/teacherSuspense.wav.meta
  Project Bunny/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  Project Bunny/Assets/Resources/NetworkCannon.prefab
  Project Bunny/Assets/Resources/NetworkCannonball.prefab
  Project Bunny/Assets/Resources/NetworkGiantRollball.prefab
  Project Bunny/Assets/Resources/NetworkIceball.prefab
  Project Bunny/Assets/Resources/NetworkPlayerTest.prefab
  Project Bunny/Assets/Resources/NetworkSnowball.prefab
  Project Bunny/Assets/Resources/NewStudent.prefab
  Project Bunny/Assets/Resources/NewTeacher.prefab
  Project Bunny/Assets/Resources/Teacher.prefab
  Project Bunny/Assets/Scenes/Networking/2-Lobby.unity
  Project Bunny/Assets/Scenes/Networking/3-Room.unity
  Project Bunny/Assets/Scenes/Networking/4-Arena.unity
  Project Bunny/Assets/Scripts/AI/Agents/Student.cs
  Project Bunny/Assets/Scripts/AI/Agents/Teacher.cs
  Project Bunny/Assets/Scripts/Networking/ArenaManager.cs
  Project Bunny/Assets/Scripts/Networking/NetworkBallonPoire.cs
  Project Bunny/Assets/Scripts/Player/NetworkCannon.cs
  Project Bunny/Assets/Scripts/Player/NetworkGiantRollball.cs
  Project Bunny/Assets/Scripts/Player/NetworkSnowball.cs
  Project Bunny/Assets/Scripts/Player/NetworkStudentController.cs
Labels: bug, Sound
